# Insert your Discord bot token.
client-token: "NTg5MDA1NDA5NTQxNTU0MjI1.XQVq7Q.3lnwpcge-iNmk4mFNdbUmwttMbg"
discord-channels:
    - 515048243365806120
    - 649423595688427540
address: "npc-network.net"