name: WhitelistDiscord
author: LimeGlass
description: A plugin that allows users to whitelist themselves on servers.
version: 1.0.2
api-version: 1.15
softdepend: [Skript]
main: me.limeglass.whitelist.WhitelistDiscord